export interface NewsArticle {
  id: number;
  title: string;
  content: string;
  category: string;
}

export const newsArticles: NewsArticle[] = [
  {
    id: 1,
    title: "Centralna banka BiH donijela plan za naredne tri godine",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "business"
  },
  {
    id: 2,
    title: "Grad Visoko će proglasiti Dan žalosti zbog današnje tragedije",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "news"
  },
  {
    id: 3,
    title: "Od danas ponovo u funkciji tramvajska linija Baščaršija-Ilidža",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "news"
  },
  {
    id: 4,
    title: "Gaming industrija u Bosni i Hercegovini raste: Novi projekti u 2025. godini",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "gaming"
  },
  {
    id: 5,
    title: "Reforme u obrazovnom sistemu BiH: Šta donosi novi zakon",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "education"
  },
  {
    id: 6,
    title: "Nove tehnologije u poljoprivredi: Inovacije koje mijenjaju industriju",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "technology"
  },
  {
    id: 7,
    title: "Veliki koncert u Sarajevu: Nastup popularnog benda iz Hrvatske",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "entertainment"
  },
  {
    id: 8,
    title: "Recept za savršen bosanski lonac: Tradicionalna jela koja morate probati",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "food"
  },
  {
    id: 9,
    title: "Moj izbor za najbolji film 2024. godine: Recenzija i preporuka",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "entertainment"
  },
  {
    id: 10,
    title: "Kako zaštititi privatnost na internetu: Vodič za početnike",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "technology"
  },
  {
    id: 11,
    title: "Zeleni gradovi: Kako graditi održive i ekološki prihvatljive gradove",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "environment"
  },
  {
    id: 12,
    title: "Fudbalska reprezentacija BiH: Najnovije vijesti i pripreme za kvalifikacije",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "sports"
  },
  {
    id: 13,
    title: "Zdravlje na prvom mjestu: Najnovije informacije o prevenciji bolesti",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "health"
  },
  {
    id: 14,
    title: "Digitalizacija u BiH: Kako nove tehnologije mijenjaju poslovanje",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "business"
  },
  {
    id: 15,
    title: "Novi trendovi u modi: Šta će biti popularno u 2025. godini",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "fashion"
  },
  {
    id: 16,
    title: "Balkanski festivali 2025: Najveći događaji na koje ne smijete zaboraviti",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "entertainment"
  },
  {
    id: 17,
    title: "Uloga umjetne inteligencije u obrazovanju: Šta nas očekuje u budućnosti?",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "education"
  },
  {
    id: 18,
    title: "Preporuke za kvalitetno putovanje: Kako uživati u odmoru bez stresa",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "travel"
  },
  {
    id: 19,
    title: "Politika u BiH: Analiza trenutnih izazova i prijedlozi rješenja",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "politics"
  },
  {
    id: 20,
    title: "Kako uspješno upravljati vremenom: Savjeti za bolju produktivnost",
    content: "Lorem ipsum odor amet, consectetuer adipiscing elit. Magna facilisi justo montes per convallis semper pretium quis risus urna ligula penatibus auctor dui lectus nec efficitur pulvinar taciti morbi dignissim in sit maecenas suspendisse consectetur ultrices aliquam aliquam ornare maecenas sed aptent vivamus libero sodales mattis dis dignissim luctus ut quisque placerat eu orci cursus curae in malesuada dictum purus dolor viverra cras tellus felis vestibulum viverra augue ligula natoque tincidunt sollicitudin blandit rutrum natoque imperdiet netus dolor ullamcorper fusce netus ut consectetur maecenas faucibus fermentum ultrices nulla odio convallis lorem est iaculis convallis rutrum himenaeos class sem nostra litora parturient volutpat porttitor nisi ut arcu vel auctor cursus porttitor volutpat potenti eleifend vivamus nam dolor hendrerit urna justo class vitae diam hendrerit himenaeos facilisis elit rutrum litora class potenti risus ante nisi auctor pellentesque ligula vestibulum gravida finibus curae fusce ridiculus dictumst maximus fames ultrices vehicula laoreet consectetur class neque eros lectus mollis lacinia finibus lacus ultrices suscipit maecenas a sit purus a nascetur laoreet est nam sapien phasellus facilisis erat eleifend lorem quis posuere odio placerat at nostra et fusce nascetur tincidunt donec est mattis ex praesent sodales fringilla arcu urna pretium a ipsum sociosqu mattis cursus id lacus blandit ultrices penatibus cras neque quisque quisque senectus fringilla netus sollicitudin praesent etiam blandit sociosqu consectetur porttitor mattis ex montes molestie cras ultricies sodales iaculis montes cras neque nascetur litora enim viverra consectetur iaculis erat vel rhoncus quam euismod eu curae a donec ac sociosqu dui class dolor iaculis fames nullam cursus volutpat dolor tempor aptent dictum nulla ad tincidunt primis interdum condimentum sem viverra vivamus ultricies praesent sodales habitant pulvinar tortor dapibus nostra ultricies ultricies suspendisse pellentesque morbi accumsan aliquam integer a morbi morbi rhoncus bibendum eleifend eget eros pulvinar maximus morbi est laoreet auctor himenaeos posuere risus odio fames montes fermentum facilisi pulvinar sodales per phasellus duis porta posuere sit quis mauris platea sed malesuada quis nunc eget cubilia tincidunt lectus ut massa quis maecenas fringilla pellentesque efficitur fermentum congue fermentum curae habitant eu sagittis tristique torquent accumsan morbi himenaeos velit posuere fames elementum sapien quis vitae augue dolor praesent eleifend viverra augue felis iaculis tellus luctus pretium imperdiet augue vitae a magnis arcu maximus diam libero inceptos facilisi finibus ut velit neque posuere nullam in malesuada semper habitant class adipiscing ligula a enim sit dictum proin parturient ultricies dui tellus nascetur mauris habitant nam finibus efficitur orci condimentum ut litora at phasellus.",
    category: "lifestyle"
  }
];
